---
# Shell is unfortunately necessary because the mysql_user module doesn't yet
# support plugin changes.
- name: Enable plugin unix_socket without unix_socket
  command: mysql -NB -s -S {{ mariadb_socket }} -u root -p{{ mariadb_current_root_password }} -e "{{ item }}"
  with_items:
    - INSTALL PLUGIN unix_socket SONAME 'auth_socket'
  register: plugin_install_result
  changed_when: plugin_install_result.rc == 0
  failed_when:
    - plugin_install_result.rc != 0
    - '"already installed" not in plugin_install_result.stderr'
  tags:
    - database
    - database-enable-plugin-unix-socket
    - mariadb
    - mariadb-enable-plugin-unix-socket

- name: Check for unix_socket in plugin column
  command: mysql -NB -s -S {{ mariadb_socket }} -u root -p{{ mariadb_current_root_password }} -e "{{ item }}"
  with_items:
    - SELECT plugin from mysql.user WHERE user = 'root'
  register: plugin_root_result
  changed_when: plugin_root_result.stdout is not search('unix_socket')
  tags:
    - database
    - database-enable-plugin-unix-socket
    - mariadb
    - mariadb-enable-plugin-unix-socket

- name: Update root user to use unix_socket
  command: mysql -NB -s -S {{ mariadb_socket }} -u root -p{{ mariadb_current_root_password }} -e "{{ item }}"
  with_items:
    - UPDATE mysql.user SET plugin = 'unix_socket' WHERE user = 'root'
    - FLUSH PRIVILEGES
  when: (plugin_root_result.stdout | default('')) is not search('unix_socket')
  tags:
    - database
    - database-enable-plugin-unix-socket
    - mariadb
    - mariadb-enable-plugin-unix-socket
