---
# Reference: https://mariadb.com/kb/en/authentication-plugin-mysql_native_password/
- name: Set root password for localhost the first time (root@localhost) and disable unix_socket plugin
  command: mysql -NB -s -S {{ mariadb_socket }} -u root -e "{{ item }}"
  with_items:
    - ALTER USER root@localhost IDENTIFIED BY '{{ mariadb_new_root_password }}';
  when:
    - unix_socket_check_result.rc == 0
    - mariadb_new_root_password | length > 0
  no_log: "{{ not ansible_check_mode }}"
  tags:
    - database
    - database-set-root-password
    - mariadb
    - mariadb-set-root-password

- name: Update root password for localhost
  command: mysql -NB -s -S {{ mariadb_socket }} -u root -p{{ mariadb_current_root_password }} -e "{{ item }}"
  with_items:
    - ALTER USER root@localhost IDENTIFIED BY '{{ mariadb_new_root_password }}'
  when:
    - unix_socket_check_result.rc != 0
    - mariadb_current_root_password | length > 0
    - mariadb_new_root_password | length > 0
  no_log: "{{ not ansible_check_mode }}"
  tags:
    - database
    - database-set-root-password
    - mariadb
    - mariadb-set-root-password

# CAUTION: debian.cnf.j2 is geenrated by pacakge installation.
# We should not edit debian.cnf...
# But this task avoid to occur an error when systemctl (re)start mariadb.
- name: Update debian.cnf
  template:
    src: "{{ ansible_facts['os_family'] }}/etc/mysql/debian.cnf.j2"
    dest: "/etc/mysql/debian.cnf"
    owner: root
    group: root
    mode: 07644
  when:
    - ansible_facts['os_family'] == 'Debian'
    - mariadb_new_root_password | length > 0
  no_log: "{{ not ansible_check_mode }}"
  notify: Restart mariadb
  tags:
    - database
    - database-set-root-password
    - mariadb
    - mariadb-set-root-password

- name: Remove unix_socket plugin if previously set the first time
  command: mysql -NB -s -S {{ mariadb_socket }} -u root -p{{ mariadb_new_root_password }} -e "{{ item }}"
  with_items:
    - UPDATE mysql.user SET plugin = '' WHERE user = 'root'
    - FLUSH PRIVILEGES
  when:
    - unix_socket_check_result.rc == 0
    - mariadb_new_root_password | length > 0
  tags:
    - database
    - database-set-root-password
    - mariadb
    - mariadb-set-root-password

- name: Update to remove unix_socket plugin if previously set
  command: mysql -NB -s -S {{ mariadb_socket }} -u root -p{{ mariadb_current_root_password }} -e "{{ item }}"
  with_items:
    - UPDATE mysql.user SET plugin = '' WHERE user = 'root'
    - FLUSH PRIVILEGES
  when:
    - unix_socket_check_result.rc == 0
    - mariadb_current_root_password | length > 0
    # This means that it updates only.
    - mariadb_new_root_password | length == 0
  tags:
    - database
    - database-set-root-password
    - mariadb
    - mariadb-set-root-password

- name: Disallow root login remotely for localhost the first time
  command: mysql -NB -s -S {{ mariadb_socket }} -u root -p{{ mariadb_new_root_password }} -e "{{ item }}"
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  when:
    - unix_socket_check_result.rc == 0
    - mariadb_new_root_password | length > 0
  changed_when: false
  notify: Restart mariadb
  tags:
    - database
    - database-set-root-password
    - mariadb
    - mariadb-set-root-password

- name: Update to disallow root login remotely
  command: mysql -NB -s -S {{ mariadb_socket }} -u root -p{{ mariadb_current_root_password }} -e "{{ item }}"
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  when:
    - unix_socket_check_result.rc != 0
    - mariadb_current_root_password | length > 0
    # This means that it updates only.
    - mariadb_new_root_password | length == 0
  changed_when: false
  notify: Restart mariadb
  tags:
    - database
    - database-set-root-password
    - mariadb
    - mariadb-set-root-password
